context: dev
contexts:
  dev:
    options:
      mount_provisioner: LocalMountProvisioner
      remove_old_config_versions_on_apply: true
      local_mount_provisioner_base_path: ./tmp/mounts

  dev_ssh:
    options:
      mount_provisioner: SshMountProvisioner
      remove_old_config_versions_on_apply: true
      ssh_mount_provisioner_base_path: /tmp/imka-dev/tmp/mounts
      ssh_mount_provisioner_hosts:
      - hostname: localhost
        port: 22
        username: user
